include: all_lint_rules.yaml

analyzer:
  exclude:
    - "vendor/**"
    - "**/*.g.dart"
    - "bin/cache/**"
    - "**/*.gen.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "lib/generated_plugin_registrant.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    deprecated_member_use_from_same_package: ignore
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: false
    avoid_catching_errors: false
    avoid_final_parameters: false
    avoid_multiple_declarations_per_line: false
    avoid_positional_boolean_parameters: false
    avoid_private_typedef_functions: false
    avoid_returning_this: false
    avoid_types_on_closure_parameters: false
    avoid_web_libraries_in_flutter: false
    cascade_invocations: false
    close_sinks: false
    comment_references: false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    diagnostic_describe_all_properties: false
    directives_ordering: false
    discarded_futures: false
    do_not_use_environment: false
    flutter_style_todos: false
    join_return_with_assignment: false
    lines_longer_than_80_chars: false
    literal_only_boolean_expressions: false
    no_runtimeType_toString: false
    omit_local_variable_types: false
    one_member_abstracts: false
    parameter_assignments: false
    prefer_asserts_with_message: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_int_literals: false
    prefer_mixin: false
    prefer_null_aware_method_calls: false
    prefer_relative_imports: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_pub_dependencies: false
    type_annotate_public_apis: false
    unawaited_futures: false
    unnecessary_final: false
    unnecessary_lambdas: false
    unnecessary_raw_strings: false
    unreachable_from_main: false
    use_decorated_box: false
    use_setters_to_change_properties: false
    use_string_buffers: false
    use_to_and_as_if_applicable: false