name: stockhauz_mobile
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  json_theme: ^6.2.6+1

  # State Mgmt
  flutter_bloc: ^8.1.3

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Routing
  beamer: ^1.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  logger: ^2.0.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  flutter_gen_runner: ^5.3.1

flutter_gen:
  fonts:
    enabled: true
    outputs:
      class_name: AppFont

  colors:
    enabled: true
    outputs:
        class_name: AppColor
    inputs:
      - assets/themes/app_color.xml

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/themes/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700